//
// Created by victorn on 09/07/18.
//

#ifndef NESTEDLOOPSEXPERIMENTS_PARAM_H


#define EXPERIMENTS_N 16
#define EXPERIMENTS_M 10
#define UT_THREAD_DEFAULT_STACK_SIZE (8U*1024U*1024U)
#define NUM_EXP 10


#define NESTEDLOOPSEXPERIMENTS_PARAM_H

#endif //NESTEDLOOPSEXPERIMENTS_PARAM_H
